### ISSUE TITLE
Potential memory leak problem of ews.run function

### ISSUE THREAD

**Issue by jeffreyleeon** [CumberlandGroup/node-ews#104]
Hi CumberlandGroup,

First thank you for developing node-ews, it saves me a lot of time interacting with email client.
Recently, I am head an issue that my production server having issue of 
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

After some research, our team found that many strings are created and persisted in the running node until all the memory used up.

![memory_leak](https://user-images.githubusercontent.com/5351758/48247286-b5d38680-e42d-11e8-9976-47f7db160b9f.png)

And we continue deep diving and found out that ews.run('FindFolder') calls caused the memory leak. Below is the sample program to reproduce the memory leak. (Version node-ews@3.2.4)

Sorry the disturb, but would like to know did we misused the library thus causing memory leak? Thank you.

```
var EWS = require('node-ews');
var cron = require('node-cron');

var ewsConfig = {
  username: 'YOUR_EMAIL',
  password: 'YOUR_PASSWORD',
  host: 'YOUR_HOST'
};

const ewsSoapHeader = {
  't:RequestServerVersion': {
    attributes: {
      Version: "Exchange2013"
    }
  }
};

const ews = new EWS(ewsConfig);

var ewsArgs = {
   'attributes' : {
      'Traversal' : 'Deep'
   },
   'FolderShape' : {
     'BaseShape': 'AllProperties'
   },
   'ParentFolderIds' : {
    'DistinguishedFolderId' : {
      'attributes' : {
        'Id' : 'inbox'
      }
    }
   }
};

function leak() {
    ews.run('FindFolder', ewsArgs, ewsSoapHeader)
      .then(result => {
        console.log(JSON.stringify(result));
      })
      .catch(err => {
        console.log(err.stack);
      });
}

cron.schedule('*/10 * * * * *', leak);
```

**Comment by samsonoveu** [comment]
Solved in [other issue](https://github.com/CumberlandGroup/node-ews/issues/77#issuecomment-375290354).

**Comment by jeffreyleeon** [comment]
Thanks @samsonoveu,
Will give this a try!
