### ISSUE TITLE
Dependency package vulnerabilities

### ISSUE THREAD

**Issue by jhenson29** [CumberlandGroup/node-ews#106]
NPM is reporting 8 vulnerabilities in the following package dependencies. 

tunnel-agent
lodash
hoek

Can these be updated and publish a patch to npm?

**Comment by Fishbowler** [comment]
I've tried this on my fork and set my package.json to "fishbowler/node-ews" as the version, but lodash appears to bomb out on the latest version 😬

**Comment by nmarus** [comment]
This has been resolved in 3.4.2.
