### ISSUE TITLE
Connection did not succeed. Try again later 

### ISSUE THREAD

**Issue by muhadel** [CumberlandGroup/node-ews#132]
I have a problem with applying any ews function, the connection did not succeed with the response code ErrorConnectionFailed.
there are two logs in the following screenshot, the first one of fetching mails and the second log of sending mail.

Ref to Microsoft exchange response codes, ErrorConnectionFailed means that an occurs when Exchange Web Services cannot connect to the mailbox

![new_error (2)](https://user-images.githubusercontent.com/32979588/95852988-f42dfa80-0d54-11eb-924f-b86467aed275.PNG)

**Comment by muhadel** [comment]
@nmarus

**Comment by nmarus** [comment]
That is on the exchange side. Perhaps a permissions issue.
