### ISSUE TITLE
Multiple attendees not working

### ISSUE THREAD

**Issue by omardlhz** [CumberlandGroup/node-ews#41]
If I add multiple attendees to a meeting, or multiple resources, only the second one gets invited. This is because two attributes in an object can't have the same key, any workaround for this?

**Comment by omardlhz** [comment]
I ended up solving this myself. Because I needed to add more than one attendee to a meeting and the object formatting doesn't work because two objects cant have the same key, I decided to pass XML directly with "$xml" (Found this in the docs of node-soap). I wrote the following function to make the attendee creation much easier.

````javascript
/**
 * Builds the XML for meeting attendees.
 *
 * @param      {array}  attendees  Array of meeting
 *             attendees in email format.
 *             
 * @return     {string}  The attendees XML.
 */
function BuildAttendees(attendees){

	var attendString = "";

	for(var i = 0; i < attendees.length; i++){

		attendString += "<t:Attendee>";
		attendString += "<t:Mailbox>";
		attendString += "<t:EmailAddress>";
		attendString += attendees[i];
		attendString += "</t:EmailAddress>";
		attendString += "</t:Mailbox>";
		attendString += "</t:Attendee>";
	}

	return attendString;
}
````

By using that function you can just pass in the meeting attendees to your ewsArgs like this:

````javascript
var ewsArgs = {
  "attributes" : {
    "SendMeetingInvitations" : "SendToAllAndSaveCopy"
  },
  "Items" : {
    "CalendarItem" : {
      "Subject" : "Test Meeting",
      "Start" : "2017-01-27T19:00:00.000-05:00",
      "End" : "2017-01-27T19:30:00.000-05:00",
      "RequiredAttendees":{
      	$xml: BuildAttendees(["test1@email.com", "test2@email.com"])
      }
    }
  }
};

````

I'm going to add this to the examples.

**Comment by bodya17** [comment]
This was really helpfull for me, thanks @omardlhz

**Comment by kcastrotech** [comment]
Thanks @omardlhz, I didn't know about the XML trick and will have to keep that in mind in the future.

However, this is related to issue/question #47 . While you are correct that an object cannot have more than one attribute with the same name, the work around that node soap uses is to assign an array as the value of the element you need multiples of in XML form. So for what you are wanting, the JSON should look like:

```
var ewsArgs = {
  "attributes" : {
    "SendMeetingInvitations" : "SendToAllAndSaveCopy"
  },
  "Items" : {
    "CalendarItem" : {
      "Subject" : "Test Meeting",
      "Start" : "2017-01-27T19:00:00.000-05:00",
      "End" : "2017-01-27T19:30:00.000-05:00",
      "RequiredAttendees":{
      	"Attendee":[
      	  {"Mailbox":{"EmailAddress":"test1@email.com"}},
       	  {"Mailbox":{"EmailAddress":"test2@email.com"}}
      	]
      }
    }
  }
};
```
Because "Attendee" has an array value, the node soap XML generator will create multiple "<Attendee>" elements.

Hope this helps!

**Comment by kcastrotech** [comment]
Another thing you may run into and which is good to keep in mind is that if you get an error about an invalid type and you know that it is valid, then you may need to force the type declaration ("**t:**") by including it in the name such as:
`{"t:Mailbox":{"t:EmailAddress":"test2@email.com"}}`
