### ISSUE TITLE
Fetching message content

### ISSUE THREAD

**Issue by mrigankulus** [CumberlandGroup/node-ews#44]
Hello,

I can get the subject and sender content while trying to get an inbox full of unread emails. Is there any way to access the actual content of the email message. I tried sending some text and it doesnt show up on the jSON returned. 

Thank You

**Comment by kcastrotech** [comment]
An example of what you're sending and what you want would be helpful.

However, if I had to guess then I'd imagine you're using FindItem (https://msdn.microsoft.com/en-us/library/office/aa566107(v=exchg.150).aspx) to get a list of unread messages and are wanting the content of said messages returned in the response? That is determined by the ItemShape (https://msdn.microsoft.com/en-us/library/office/aa565261(v=exchg.150).aspx) specified in your request. So you'll either need to change the BaseShape to "AllProperties" or use the "AdditionalProperties" to specify the specific properties (https://msdn.microsoft.com/en-us/library/office/dn600367(v=exchg.150).aspx) you want returned.

**Comment by mrigankulus** [comment]
Ah got it. Thank You!

**Comment by kcastrotech** [comment]
You're welcome! :)
