### ISSUE TITLE
How to set Importance to High when sending e-mail?

### ISSUE THREAD

**Issue by lokanx** [CumberlandGroup/node-ews#52]
Hi!
Trying to send an e-mail with importance set to high.
Been trying adding the following to your example code but none works.

Attempt 1:
"Importance": "hight"

Attemp 2: 
"Importance:  {"$value": "High"}

Any idea how to do this?

// Cheers B

**Comment by kcastrotech** [comment]
https://msdn.microsoft.com/en-us/library/office/aa563467(v=exchg.150).aspx
Your first attempt should be correct, though you have a typo of "hight" which should be "High".

Are you getting an error when you attempt to send?

**Comment by lokanx** [comment]
Hi!
Thanks for the reply, yes I got some error response back with my attempts. Will do a new attempt ASAP with correct spelling and let you know. // Cheers B

**Comment by lokanx** [comment]
Hi again!
It surely works better if you spell things correctly, how stupid of me.
This works like a charm:

      "Message" : {
       ...
        "Importance": "High",
       ...
      }

Thanks again for the response and for the great library.

// Cheers B

**Comment by kcastrotech** [comment]
Happy to help! 😄
