### ISSUE TITLE
Get events of a user

### ISSUE THREAD

**Issue by romainpa** [CumberlandGroup/node-ews#75]
Hello,

I try to get appointments of a specific mailbox like "what is my next meeting".

I've seen online documentation like https://msdn.microsoft.com/en-us/library/office/dn495614(v=exchg.150).aspx
But on my ews/Services.wsdl, I got nothing regarding Calendar or Appointments. 

Any idea of the way to do it ?

Thanks,

**Comment by kcastrotech** [comment]
The instructions in the link you provided works fine for me.

1. Run GetFolder to get the folder ID and ChangeKey for the calendar folder.
2. Run FindItem to get the items for the folder specified in step 1.

What seems to be the issue?

**Comment by OCWs-Outillage** [comment]
In fact, using your recommendations it works. I wasn't using the good way to solve my need

**Comment by romainpa** [comment]
In fact, using your recommendations it works. I wasn't using the good way to solve my need.

**Comment by kcastrotech** [comment]
Glad you got it working.

**Comment by niclego** [comment]
Do you know why this would not be returning a subject on the CalanderItems?
![screen shot 2018-06-25 at 10 00 21 am](https://user-images.githubusercontent.com/10523557/41864375-9f2293a8-785e-11e8-80af-0617b02c19a6.png)
