### ISSUE TITLE
Error: EWS lets node run out of memory and increase CPU Load to 100%

### ISSUE THREAD

**Issue by stephankoeppen** [CumberlandGroup/node-ews#77]
Hey,

i'm experiencing an issues, where the EWS Module lets Node hang (Memory increase und CPU Load over 100%). I'm iterating through an array and want to create all these accounts in the specified Exchange Account. The execution of the EWS requests is done sequentially. I don't get any errors in the log on development (Mac + Webstorm). Just that it eventually hangs. On production at some point I get a memory allocation error within the logs and the application restarts. Unfortunately I can't see whats going on within the EWS or what would produce that kind of behavior. 

I hope, someone can help me. 

Best regards,
Stephan

**Comment by nmarus** [comment]
Can you share the EWS request that you are making?

**Comment by echetzakis** [comment]
I had similar issues with a node app and figured out that the memory leak was related wit the WSDL being downloaded and kept into a string var in memory each time you create an EWS instance. 

Solved by adding a `temp` option in the the config like so:
```
const EWS = require('node-ews');
 
// exchange server connection info
const ewsConfig = {
  username: 'myuser@domain.com',
  password: 'mypassword',
  host: 'https://ews.domain.com',
  temp: '/tmp'
};
 
const ews = new EWS(ewsConfig);
```
