### ISSUE TITLE
Read Unread mail with Body and attachment

### ISSUE THREAD

**Issue by renjithpta** [CumberlandGroup/node-ews#82]
Hi,
Can you help in writing code to get unread mail with body as text and download attachment.

**Comment by kcastrotech** [comment]
This area is meant for problems/issues experienced when using Node-EWS. If you need general How-To help with using the package then I suggest you read through the many examples given in the ReadMe and in the resolved issues. I also suggest you read through Microsoft's EWS operations in Exchange (https://github.com/CumberlandGroup/node-ews/).
