### ISSUE TITLE
AdditionalProperties only returns last FieldURI

### ISSUE THREAD

**Issue by niclego** [CumberlandGroup/node-ews#93]
![screen shot 2018-06-25 at 4 19 03 pm](https://user-images.githubusercontent.com/10523557/41880551-82ecad60-7893-11e8-8a83-5b54f4f4eb21.png)

The response data from this EWS call only contains the starting time of each calender event and no end time. If i switch the FieldURI's so that end is last, the response data only contains the end time of each event. 

Is this how node-ews was designed?

**Comment by WirecardMobileServices** [comment]
As per #24 	the FieldURI should contain the array of fields
`
'FieldURI': [
		{ 'attributes': { 'FieldURI': 'item:Subject'}},
		{ 'attributes': { 'FieldURI': 'calendar:Start'}},
		{ 'attributes': { 'FieldURI': 'calendar:End'}}
	]
`
