### ISSUE TITLE
Error: connect EACCES 127.0.0.1:80

### ISSUE THREAD

**Issue by yannDroy** [CumberlandGroup/node-ews#97]
I copied pasted example 4 to send an email and here is what I got:

Error: connect EACCES 127.0.0.1:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

Is it possible to change the port? I guess that's where the problem comes from, port < 1024

EDIT: I'm trying to to send an email in an application hosted on Azure

**Comment by dzhivushko** [comment]
Hello @JasonBBelcher,
is it possible to add the brief reason why this closed? is it some kind of misconfiguration or what?

**Comment by dzhivushko** [comment]
I found the misconfiguration. I provided the protocol in 'host' property - only domain was specified. This is a cause of redirect to localhost.
